---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: operatehappy/packer-github-action
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-action
        with:
          command: validate
          arguments: -syntax-only
          target: artifacts.pkr.json packer.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-action
        with:
          command: build
          arguments: "-color=false -on-error=abort
      env:
        MY_NAME: "Rick Smith"
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
