name: HashiCorp Packer
on: [push]

jobs:
  build:
    MY_NAME: "Rick Smith"
    AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    name: Packer Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:

        
